package codegen

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nseba/structql/internal/config"
	"github.com/nseba/structql/internal/query"
	"github.com/nseba/structql/internal/schema"
)

var update = flag.Bool("update", false, "update golden files")

func TestGenerator_FullPipeline(t *testing.T) {
	sch, err := schema.Load([]string{"../../testdata/schemas/starwars.graphql"})
	if err != nil {
		t.Fatalf("loading schema: %v", err)
	}

	ops, err := query.Load("../../testdata/queries", sch)
	if err != nil {
		t.Fatalf("loading queries: %v", err)
	}

	cfg := &config.Config{
		Package: "starwars",
		Scalars: map[string]config.ScalarConfig{},
	}

	gen := New(cfg, sch)
	files, err := gen.Generate(ops)
	if err != nil {
		t.Fatalf("generating: %v", err)
	}

	if len(files) == 0 {
		t.Fatal("expected generated files")
	}

	// Verify we have operation files + types.go
	hasTypes := false
	for _, f := range files {
		if f.Name == "types.go" {
			hasTypes = true
		}

		// Verify each file is valid Go (formatSource would have failed otherwise)
		content := string(f.Content)
		if !strings.HasPrefix(content, "// Code generated by structql") {
			t.Errorf("file %s missing generated header", f.Name)
		}
		if !strings.Contains(content, "package starwars") {
			t.Errorf("file %s missing package declaration", f.Name)
		}

		// Golden file testing
		goldenPath := filepath.Join("../../testdata/golden", f.Name+".golden")
		if *update {
			if err := os.MkdirAll(filepath.Dir(goldenPath), 0755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(goldenPath, f.Content, 0644); err != nil {
				t.Fatalf("updating golden file %s: %v", goldenPath, err)
			}
			continue
		}

		golden, err := os.ReadFile(goldenPath)
		if err != nil {
			t.Logf("golden file %s not found, run with -update to create", goldenPath)
			continue
		}

		if string(f.Content) != string(golden) {
			t.Errorf("file %s does not match golden file.\n\nGot:\n%s\n\nExpected:\n%s", f.Name, f.Content, golden)
		}
	}

	if !hasTypes {
		t.Error("expected types.go in output")
	}
}

func TestGenerator_EmptyOperations(t *testing.T) {
	sch, err := schema.Load([]string{"../../testdata/schemas/starwars.graphql"})
	if err != nil {
		t.Fatalf("loading schema: %v", err)
	}

	cfg := &config.Config{
		Package: "empty",
		Scalars: map[string]config.ScalarConfig{},
	}

	gen := New(cfg, sch)
	files, err := gen.Generate(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(files) != 0 {
		t.Errorf("expected 0 files for empty operations, got %d", len(files))
	}
}
