package codegen

import (
	"strings"
	"testing"
)

func TestRenderOperation_Simple(t *testing.T) {
	data := &OperationData{
		PackageName:   "testpkg",
		OperationName: "GetUser",
		OperationType: "query",
		Fields: []*StructField{
			{
				Name:   "User",
				GoType: "struct",
				Tag:    "user(id: $id)",
				Children: []*StructField{
					{Name: "Name", GoType: "string"},
					{Name: "Email", GoType: "string"},
				},
			},
		},
		Variables: []*VariableField{
			{GraphQLName: "id", GoName: "ID", GoType: "graphql.ID", NonNull: true},
		},
		Imports:      []string{graphqlClientPkg},
		NeedsGraphQL: true,
	}

	src, err := RenderOperation(data)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	code := string(src)

	// Check key elements are present
	checks := []string{
		"Code generated by structql",
		"package testpkg",
		"type GetUser struct",
		"User struct {",
		"Name  string",
		"Email string",
		`graphql:"user(id: $id)"`,
		"func GetUserVariables(",
		`"id": id,`,
	}

	for _, check := range checks {
		if !strings.Contains(code, check) {
			t.Errorf("expected output to contain %q\n\nGot:\n%s", check, code)
		}
	}
}

func TestRenderTypes_Enums(t *testing.T) {
	data := &TypesData{
		PackageName: "testpkg",
		Enums: []*EnumData{
			{
				Name:    "Status",
				Comment: "Status represents the GraphQL enum Status.",
				Values: []*EnumValue{
					{GoName: "StatusActive", Value: "ACTIVE", EnumTypeName: "Status"},
					{GoName: "StatusInactive", Value: "INACTIVE", EnumTypeName: "Status"},
				},
			},
		},
	}

	src, err := RenderTypes(data)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	code := string(src)

	checks := []string{
		"Code generated by structql",
		"package testpkg",
		"type Status string",
		`StatusActive   Status = "ACTIVE"`,
		`StatusInactive Status = "INACTIVE"`,
	}

	for _, check := range checks {
		if !strings.Contains(code, check) {
			t.Errorf("expected output to contain %q\n\nGot:\n%s", check, code)
		}
	}
}

func TestRenderTypes_Nil(t *testing.T) {
	data := &TypesData{
		PackageName: "testpkg",
	}

	src, err := RenderTypes(data)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if src != nil {
		t.Error("expected nil for empty types")
	}
}

func TestLowerFirst(t *testing.T) {
	tests := []struct {
		input, want string
	}{
		{"Name", "name"},
		{"ID", "id"},
		{"episode", "episode"},
		{"", ""},
	}

	for _, tt := range tests {
		got := lowerFirst(tt.input)
		if got != tt.want {
			t.Errorf("lowerFirst(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}
