package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"golang.org/x/tools/imports"
)

const generatedHeader = "// Code generated by structql. DO NOT EDIT."

var funcMap = template.FuncMap{
	"join": strings.Join,
}

var operationTmpl = template.Must(template.New("operation").Funcs(funcMap).Parse(`{{ .Header }}
package {{ .PackageName }}
{{ range .ImportLines }}
{{ . }}
{{ end }}
// {{ .OperationName }} represents the GraphQL {{ .OperationType }} {{ .OperationName }}.
type {{ .OperationName }} struct {
{{ .StructBody }}
}
{{ if .Variables }}
// {{ .OperationName }}Variables returns the variables for {{ .OperationName }}.
func {{ .OperationName }}Variables({{ .FuncParams }}) map[string]interface{} {
	return map[string]interface{}{
{{ .VarMapEntries }}
	}
}
{{ end }}
`))

var typesTmpl = template.Must(template.New("types").Funcs(funcMap).Parse(`{{ .Header }}
package {{ .PackageName }}
{{ range .ImportLines }}
{{ . }}
{{ end }}
{{ range .Enums }}
// {{ .Comment }}
type {{ .Name }} string

const (
{{ range $v := .Values }}	{{ $v.GoName }} {{ $v.EnumTypeName }} = "{{ $v.Value }}"
{{ end }})
{{ end }}
{{ range .InputTypes }}
// {{ .Comment }}
type {{ .Name }} struct {
{{ range .Fields }}	{{ .GoName }} {{ .GoType }} ` + "`" + `json:"{{ .JSONTag }}"` + "`" + `
{{ end }}}
{{ end }}
`))

// RenderOperation renders an operation to formatted Go source.
func RenderOperation(data *OperationData) ([]byte, error) {
	body := renderStructFields(data.Fields, 1)

	var importLines []string
	if len(data.Imports) > 0 {
		importLines = append(importLines, "import (")
		for _, imp := range data.Imports {
			if imp == graphqlClientPkg {
				importLines = append(importLines, fmt.Sprintf("\tgraphql %q", imp))
			} else {
				importLines = append(importLines, fmt.Sprintf("\t%q", imp))
			}
		}
		importLines = append(importLines, ")")
	}

	funcParams := renderFuncParams(data.Variables)
	varEntries := renderVarMapEntries(data.Variables)

	var buf bytes.Buffer
	err := operationTmpl.Execute(&buf, map[string]interface{}{
		"Header":        generatedHeader,
		"PackageName":   data.PackageName,
		"ImportLines":   importLines,
		"OperationName": data.OperationName,
		"OperationType": data.OperationType,
		"StructBody":    body,
		"Variables":     data.Variables,
		"FuncParams":    funcParams,
		"VarMapEntries": varEntries,
	})
	if err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	return formatSource(buf.Bytes())
}

// RenderTypes renders the shared types file to formatted Go source.
func RenderTypes(data *TypesData) ([]byte, error) {
	if len(data.Enums) == 0 && len(data.InputTypes) == 0 {
		return nil, nil
	}

	var importLines []string
	if data.NeedsGraphQL {
		importLines = append(importLines, "import (")
		importLines = append(importLines, fmt.Sprintf("\tgraphql %q", graphqlClientPkg))
		importLines = append(importLines, ")")
	}

	var buf bytes.Buffer
	err := typesTmpl.Execute(&buf, map[string]interface{}{
		"Header":      generatedHeader,
		"PackageName": data.PackageName,
		"ImportLines": importLines,
		"Enums":       data.Enums,
		"InputTypes":  data.InputTypes,
	})
	if err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	return formatSource(buf.Bytes())
}

func renderStructFields(fields []*StructField, depth int) string {
	indent := strings.Repeat("\t", depth)
	var lines []string

	for _, f := range fields {
		if len(f.Children) > 0 {
			// Nested struct
			childBody := renderStructFields(f.Children, depth+1)
			tag := buildTag(f)
			prefix := ""
			if f.IsPtr && f.IsList {
				prefix = "*[]"
			} else if f.IsList {
				prefix = "[]"
			} else if f.IsPtr {
				prefix = "*"
			}
			lines = append(lines, fmt.Sprintf("%s%s %sstruct {\n%s\n%s}%s", indent, f.Name, prefix, childBody, indent, tag))
		} else {
			tag := buildTag(f)
			lines = append(lines, fmt.Sprintf("%s%s %s%s", indent, f.Name, f.GoType, tag))
		}
	}

	return strings.Join(lines, "\n")
}

func buildTag(f *StructField) string {
	var tags []string
	if f.Tag != "" {
		tags = append(tags, fmt.Sprintf(`graphql:"%s"`, f.Tag))
	}
	if f.IsScalar {
		tags = append(tags, `scalar:"true"`)
	}
	if len(tags) == 0 {
		return ""
	}
	return " `" + strings.Join(tags, " ") + "`"
}

func renderFuncParams(vars []*VariableField) string {
	var params []string
	for _, v := range vars {
		params = append(params, fmt.Sprintf("%s %s", lowerFirst(v.GoName), v.GoType))
	}
	return strings.Join(params, ", ")
}

func renderVarMapEntries(vars []*VariableField) string {
	var entries []string
	for _, v := range vars {
		entries = append(entries, fmt.Sprintf("\t\t%q: %s,", v.GraphQLName, lowerFirst(v.GoName)))
	}
	return strings.Join(entries, "\n")
}

func lowerFirst(s string) string {
	if s == "" {
		return ""
	}
	// Handle acronyms like "ID" -> "id"
	if len(s) >= 2 && s[0] >= 'A' && s[0] <= 'Z' && s[1] >= 'A' && s[1] <= 'Z' {
		return strings.ToLower(s)
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func formatSource(src []byte) ([]byte, error) {
	// First try gofmt
	formatted, err := format.Source(src)
	if err != nil {
		// Return the unformatted source with the error for debugging
		return src, fmt.Errorf("gofmt: %w\nsource:\n%s", err, string(src))
	}

	// Then run goimports to fix imports
	result, err := imports.Process("", formatted, nil)
	if err != nil {
		// gofmt succeeded but goimports failed, return gofmt result
		return formatted, nil
	}

	return result, nil
}
