package output

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/nseba/structql/internal/codegen"
)

func TestWrite_CreatesFiles(t *testing.T) {
	dir := t.TempDir()
	mgr := NewManager(dir)

	files := []*codegen.GeneratedFile{
		{Name: "test.go", Content: []byte("// Code generated by structql. DO NOT EDIT.\npackage test\n")},
	}

	if err := mgr.Write(files); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "test.go"))
	if err != nil {
		t.Fatalf("reading written file: %v", err)
	}
	if string(content) != "// Code generated by structql. DO NOT EDIT.\npackage test\n" {
		t.Errorf("unexpected content: %s", content)
	}
}

func TestWrite_RemovesObsolete(t *testing.T) {
	dir := t.TempDir()

	// Create an existing generated file
	obsolete := filepath.Join(dir, "old.go")
	if err := os.WriteFile(obsolete, []byte("// Code generated by structql. DO NOT EDIT.\npackage test\n"), 0644); err != nil {
		t.Fatal(err)
	}

	mgr := NewManager(dir)
	files := []*codegen.GeneratedFile{
		{Name: "new.go", Content: []byte("// Code generated by structql. DO NOT EDIT.\npackage test\n")},
	}

	if err := mgr.Write(files); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Old file should be removed
	if _, err := os.Stat(obsolete); !os.IsNotExist(err) {
		t.Error("obsolete file should have been removed")
	}

	// New file should exist
	if _, err := os.Stat(filepath.Join(dir, "new.go")); err != nil {
		t.Error("new file should exist")
	}
}

func TestWrite_PreservesNonGenerated(t *testing.T) {
	dir := t.TempDir()

	// Create a user-written file
	userFile := filepath.Join(dir, "custom.go")
	if err := os.WriteFile(userFile, []byte("package test\n\nfunc Custom() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	mgr := NewManager(dir)
	files := []*codegen.GeneratedFile{
		{Name: "gen.go", Content: []byte("// Code generated by structql. DO NOT EDIT.\npackage test\n")},
	}

	if err := mgr.Write(files); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// User file should still exist
	if _, err := os.Stat(userFile); err != nil {
		t.Error("user-written file should be preserved")
	}
}

func TestWrite_CreatesOutputDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "output")
	mgr := NewManager(dir)

	files := []*codegen.GeneratedFile{
		{Name: "test.go", Content: []byte("// Code generated by structql. DO NOT EDIT.\npackage test\n")},
	}

	if err := mgr.Write(files); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "test.go")); err != nil {
		t.Error("file should exist in created directory")
	}
}
