// Package output manages writing generated files and cleaning up obsolete ones.
package output

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nseba/structql/internal/codegen"
)

const generatedMarker = "// Code generated by structql. DO NOT EDIT."

// Manager handles writing generated files and cleaning up obsolete ones.
type Manager struct {
	outputDir string
}

// NewManager creates a new output Manager.
func NewManager(outputDir string) *Manager {
	return &Manager{outputDir: outputDir}
}

// Write writes all generated files and removes obsolete ones.
func (m *Manager) Write(files []*codegen.GeneratedFile) error {
	if err := os.MkdirAll(m.outputDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	// Track what we're writing
	written := make(map[string]bool)

	for _, f := range files {
		path := filepath.Join(m.outputDir, f.Name)
		if err := os.WriteFile(path, f.Content, 0644); err != nil {
			return fmt.Errorf("writing %s: %w", f.Name, err)
		}
		written[f.Name] = true
	}

	// Clean up obsolete generated files
	return m.cleanObsolete(written)
}

func (m *Manager) cleanObsolete(current map[string]bool) error {
	entries, err := os.ReadDir(m.outputDir)
	if err != nil {
		return fmt.Errorf("reading output directory: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}

		if current[entry.Name()] {
			continue
		}

		path := filepath.Join(m.outputDir, entry.Name())
		if isGenerated(path) {
			if err := os.Remove(path); err != nil {
				return fmt.Errorf("removing obsolete file %s: %w", entry.Name(), err)
			}
		}
	}

	return nil
}

func isGenerated(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	if scanner.Scan() {
		return strings.TrimSpace(scanner.Text()) == generatedMarker
	}
	return false
}
